package by.jwd.restaurant.controller.command;

public enum CommandName {
    LOGIN,
    LOGOUT,
    GOTOHOMEPAGE,
    GOTOLOGINPAGE,
    GOTOMAINPAGE,
    SAVENEWUSER,
    REGISTRATION,
    EN,
    RU,
    ADDNEWDISH,
    GOTOADDDISHPAGE,
    GOTOMENUPAGE,
    MAKEORDER,
    ADDTOORDER,
    DELETEDISH,
    DELETEDISHINORDER,
    UPDATEDISH,
    ORDERDISH,
    GOTOEDITDISHPAGE,
    MAKENEWORDER,
    GOTOGALLERYPAGE,
    GOTOABOUTPAGE,
    GOTOMAKEORDERPAGE,
    GOTORESERVATIONPAGE,
    GOTOUSERORDERSPAGE

}
